version: '3.8'

services:
  php:
    build:
      context: .          # Ruta a tu Dockerfile (raíz del proyecto)
      dockerfile: Dockerfile
    container_name: php_container
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=contraseña
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contraseña
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
